# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: fuffaos
description: OS image by Flower - ThinkPad Ryzen Edition.
base-image: ghcr.io/ublue-os/bazzite
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    install:
      - fprintd
      - fprintd-pam
      - libfprint
      - thinkfan
      - fwupd
      - gcc
      - make
      - cmake
      - kernel-devel
      - libusb1-devel
      - usbutils
      - brightnessctl
    remove:
      - firefox
      - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - com.google.Chrome
        remove:
          - org.mozilla.firefox

  - type: script
    scripts:
      - thinkpad-setup.sh

  - type: signing