# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: fuffaos
description: OS image by Flower - ThinkPad Ryzen Edition.

base-image: ghcr.io/ublue-os/bazzite
image-version: latest

modules:
  - type: files
    files:
      - source: files/system
        destination: /

  - type: rpm-ostree
    repos:
      - https://dl.google.com/linux/chrome/rpm/stable/x86_64
    install:
      # Browser
      - google-chrome-stable
      # Supporto ThinkPad e Impronte Digitali
      - fprintd
      - fprintd-pam
      - libfprint
      # Sviluppo (Base-devel / USB-devel)
      - gcc
      - gcc-c++
      - make
      - automake
      - autoconf
      - cmake
      - git
      - binutils
      - kernel-devel
      - libusb1-devel
      - usbutils
      # Utility Hardware
      - brightnessctl
    remove:
      - firefox
      - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        remove:
          - org.mozilla.firefox # Rimuove il flatpak preinstallato

  - type: script
    scripts:
      - thinkpad-setup.sh # BlueBuild cercherà questo file dentro files/scripts/

  - type: signing